import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from models.opinion_analyzer import analyze_opinion


explizite = [
    "I think the government should invest more in education.",
    "In my opinion, climate change is the biggest threat we face.",
    "I believe healthcare should be free for everyone.",
    "I feel that taxes are too high in this country.",
    "For me, remote work is much more productive.",
    "I'm convinced that electric cars are the future.",
    "I strongly believe that social media does more harm than good.",
    "I think our politicians are not listening to the people.",
    "In my view, the housing market is completely broken.",
    "I feel the public transport system needs urgent improvement.",
    "I believe the school curriculum is outdated.",
    "For me, privacy online is a basic right.",
    "I think the food quality in supermarkets is declining.",
    "In my opinion, the internet should be regulated.",
    "I feel that mental health is not taken seriously enough.",
    "I'm convinced that renewable energy is the only way forward.",
    "I strongly believe that animal testing should be banned.",
    "I think the cost of living is unbearable.",
    "In my view, the justice system is unfair.",
    "I feel the media is too biased.",
    "I believe that voting should be mandatory.",
    "For me, art is essential for society.",
    "I think the city needs more green spaces.",
    "In my opinion, the education system fails many students.",
    "I feel that technology is moving too fast.",
    "I'm convinced that universal basic income is necessary.",
    "I strongly believe that everyone deserves a second chance.",
    "I think the healthcare system is broken.",
    "In my view, the police should be better trained.",
    "I feel the environment is being neglected.",
    "I believe that science should guide policy.",
    "For me, freedom of speech is non-negotiable.",
    "I think the minimum wage should be higher.",
    "In my opinion, the fashion industry is wasteful.",
    "I feel that sports unite people.",
    "I'm convinced that democracy is under threat.",
    "I strongly believe that recycling should be compulsory.",
    "I think the internet is both a blessing and a curse.",
    "In my view, the pension system needs reform.",
    "I feel the government should support small businesses.",
    "I believe that public libraries are vital.",
    "For me, travel broadens the mind.",
    "I think the healthcare workers are underpaid.",
    "In my opinion, the justice system needs transparency.",
    "I feel that education should be lifelong.",
    "I'm convinced that climate action can't wait.",
    "I strongly believe that kindness is underrated.",
    "I think the city should invest in bike lanes.",
    "In my view, the arts need more funding.",
    "I feel the news is too negative."
]

implizite = [
    "The government ignores the needs of students.",
    "Climate change threatens our future.",
    "Healthcare costs are out of control.",
    "Taxes keep rising every year.",
    "Remote work increases productivity.",
    "Electric cars will replace gasoline vehicles soon.",
    "Social media spreads misinformation.",
    "Politicians rarely listen to ordinary people.",
    "The housing market is unaffordable.",
    "Public transport is unreliable.",
    "School curriculum doesn't prepare students for real life.",
    "Online privacy is constantly violated.",
    "Food quality in supermarkets is getting worse.",
    "Internet regulation is necessary.",
    "Mental health is often overlooked.",
    "Renewable energy is the only sustainable option.",
    "Animal testing is cruel.",
    "Living costs are unbearable for many.",
    "Justice system fails to protect the innocent.",
    "Media coverage is biased.",
    "Voting rates are too low.",
    "Art is undervalued in society.",
    "City lacks green spaces.",
    "Education system leaves many behind.",
    "Technology advances too quickly.",
    "Universal basic income could solve poverty.",
    "Everyone deserves another chance.",
    "Healthcare system doesn't work.",
    "Police training is insufficient.",
    "Environment is neglected.",
    "Science should influence decisions.",
    "Freedom of speech is at risk.",
    "Minimum wage is too low.",
    "Fashion industry creates too much waste.",
    "Sports bring people together.",
    "Democracy faces new challenges.",
    "Recycling rates are disappointing.",
    "Internet has both positive and negative effects.",
    "Pension system is outdated.",
    "Small businesses need more support.",
    "Public libraries are disappearing.",
    "Travel changes perspectives.",
    "Healthcare workers are underappreciated.",
    "Justice system lacks transparency.",
    "Education should continue throughout life.",
    "Climate action is urgent.",
    "Kindness is rare nowadays.",
    "Bike lanes are missing in the city.",
    "Arts funding is insufficient.",
    "News focuses too much on negativity."
       "The government fails to address housing shortages.",
    "Climate change is making summers unbearable.",
    "Healthcare is too expensive for most people.",
    "Taxes are a burden for small businesses.",
    "Remote work is the future of employment.",
    "Electric cars are overrated by the media.",
    "Social media is ruining real conversations.",
    "Politicians ignore the voices of the youth.",
    "The housing market is broken beyond repair.",
    "Public transport is always late.",
    "School curriculum doesn't reflect modern needs.",
    "Online privacy is a myth nowadays.",
    "Food quality in stores keeps declining.",
    "Internet regulation is long overdue.",
    "Mental health is not prioritized enough.",
    "Renewable energy is the only hope.",
    "Animal testing should be stopped immediately.",
    "Living costs are crushing families.",
    "Justice system protects the powerful.",
    "Media coverage is always sensationalized.",
    "Voting rates are disappointingly low.",
    "Art is not valued in our society.",
    "City planning ignores green spaces.",
    "Education system leaves students behind.",
    "Technology is advancing too fast for comfort.",
    "Universal basic income is the solution to poverty.",
    "Everyone deserves a second chance in life.",
    "Healthcare system is failing patients.",
    "Police training is insufficient for real challenges.",
    "Environment is neglected by policymakers.",
    "Science should be the basis for decisions.",
    "Freedom of speech is under threat.",
    "Minimum wage is not enough to live on.",
    "Fashion industry is wasteful and polluting.",
    "Sports unite people across cultures.",
    "Democracy is facing serious challenges.",
    "Recycling rates are far too low.",
    "Internet brings both good and bad.",
    "Pension system is outdated and unfair.",
    "Small businesses struggle to survive.",
    "Public libraries are disappearing fast.",
    "Travel broadens perspectives.",
    "Healthcare workers are undervalued.",
    "Justice system lacks transparency.",
    "Education should be lifelong.",
    "Climate action can't wait any longer.",
    "Kindness is rare in today's world.",
    "Bike lanes are missing everywhere.",
    "Arts funding is always insufficient.",
    "News is too focused on negativity.",
    "Government ignores rural communities.",
    "Climate policies are too weak.",
    "Healthcare reforms are always delayed.",
    "Tax system favors the rich.",
    "Remote work increases inequality.",
    "Electric cars are too expensive.",
    "Social media spreads hate.",
    "Politicians make empty promises.",
    "Housing costs are out of control.",
    "Public transport is overcrowded.",
    "School curriculum is outdated.",
    "Online privacy is constantly violated.",
    "Food prices keep rising.",
    "Internet is full of misinformation.",
    "Mental health is stigmatized.",
    "Renewable energy is underfunded.",
    "Animal rights are ignored.",
    "Living costs rise faster than wages.",
    "Justice system is slow.",
    "Media is biased towards certain parties.",
    "Voting is too complicated.",
    "Art is underfunded.",
    "City lacks affordable housing.",
    "Education system is too rigid.",
    "Technology replaces jobs.",
    "Universal basic income is controversial.",
    "Everyone faces discrimination.",
    "Healthcare access is unequal.",
    "Police are not trusted.",
    "Environment suffers from neglect.",
    "Science is politicized.",
    "Freedom of speech is abused.",
    "Minimum wage debates go nowhere.",
    "Fashion industry exploits workers.",
    "Sports are commercialized.",
    "Democracy is fragile.",
    "Recycling is inconvenient.",
    "Internet addiction is rising.",
    "Pension system is unsustainable.",
    "Small businesses face bureaucracy.",
    "Public libraries lack funding.",
    "Travel is becoming unaffordable.",
    "Healthcare workers are exhausted.",
    "Justice system is inconsistent.",
    "Education is too expensive.",
    "Climate action is politicized.",
    "Kindness is undervalued.",
    "Bike lanes are unsafe.",
    "Arts are neglected.",
    "News is sensationalist."
]

informationen = [
    "The government announced a new education policy today.",
    "Global temperatures increased by 1.2°C since 1900.",
    "Healthcare spending reached $3 trillion last year.",
    "The tax rate for 2024 is 25%.",
    "Remote work became common during the pandemic.",
    "Electric cars accounted for 10% of new sales in 2023.",
    "Social media platforms have over 3 billion users.",
    "The parliament passed a new housing bill.",
    "Average rent in the city is $1200 per month.",
    "Public transport includes buses, trains, and trams.",
    "School curriculum covers math, science, and history.",
    "Online privacy laws were updated in 2022.",
    "Supermarkets offer organic food options.",
    "Internet usage grew by 5% last year.",
    "Mental health services are available in all hospitals.",
    "Renewable energy sources include wind and solar.",
    "Animal testing is regulated by law.",
    "Cost of living index rose by 2 points.",
    "Justice system reforms were proposed.",
    "Media outlets reported on the election.",
    "Voting is held every four years.",
    "Art exhibitions are open to the public.",
    "City parks cover 500 hectares.",
    "Education system consists of primary and secondary schools.",
    "Technology companies released new products.",
    "Universal basic income was discussed in parliament.",
    "Second chance programs are available for ex-offenders.",
    "Healthcare system includes clinics and hospitals.",
    "Police training lasts six months.",
    "Environmental protection laws were strengthened.",
    "Science conferences are held annually.",
    "Freedom of speech is protected by the constitution.",
    "Minimum wage increased by 1 dollar.",
    "Fashion industry exports rose by 8%.",
    "Sports events attract thousands of fans.",
    "Democracy index improved in 2023.",
    "Recycling centers opened in five districts.",
    "Internet speed averages 100 Mbps.",
    "Pension system covers all citizens.",
    "Small businesses employ 40% of the workforce.",
    "Public libraries offer free Wi-Fi.",
    "Travel restrictions were lifted in June.",
    "Healthcare workers received bonuses.",
    "Justice system statistics were published.",
    "Education programs are available online.",
    "Climate action plans were announced.",
    "Kindness campaigns started in schools.",
    "Bike lanes were expanded last year.",
    "Arts funding increased by 10%.",
    "News channels broadcast 24 hours a day."
      "The government announced a new housing initiative.",
    "Average summer temperatures reached 30°C last year.",
    "Healthcare spending increased by 5% in 2024.",
    "The tax rate for small businesses is 18%.",
    "Remote work policies were updated in 2023.",
    "Electric cars made up 12% of new registrations.",
    "Social media platforms launched new privacy features.",
    "Parliament passed the education reform bill.",
    "Median house price is $350,000.",
    "Public transport includes metro, buses, and trams.",
    "School curriculum now includes coding.",
    "Online privacy laws were revised in 2022.",
    "Food prices rose by 3% last quarter.",
    "Internet usage reached 85% of households.",
    "Mental health services expanded in rural areas.",
    "Renewable energy accounted for 40% of electricity.",
    "Animal testing regulations were updated.",
    "Living costs index increased by 1.5 points.",
    "Justice system reforms were debated in parliament.",
    "Media outlets reported on the climate summit.",
    "Voting turnout was 62% in the last election.",
    "Art exhibitions attracted 20,000 visitors.",
    "City parks cover 600 hectares.",
    "Education system includes vocational training.",
    "Technology companies invested $2B in research.",
    "Universal basic income pilot started in 2025.",
    "Second chance programs supported 5,000 people.",
    "Healthcare system includes emergency clinics.",
    "Police training lasts eight months.",
    "Environmental protection laws were strengthened.",
    "Science conferences hosted 1,200 participants.",
    "Freedom of speech is guaranteed by law.",
    "Minimum wage increased to $12 per hour.",
    "Fashion industry exports reached $1B.",
    "Sports events were held in 15 cities.",
    "Democracy index rose by 2 points.",
    "Recycling centers processed 50,000 tons of waste.",
    "Internet speed averages 120 Mbps.",
    "Pension system covers 95% of retirees.",
    "Small businesses employ 35% of workers.",
    "Public libraries offer digital books.",
    "Travel restrictions were lifted in July.",
    "Healthcare workers received training bonuses.",
    "Justice system statistics published in May.",
    "Education programs available in five languages.",
    "Climate action plans released for 2030.",
    "Kindness campaigns started in 50 schools.",
    "Bike lanes expanded by 20 kilometers.",
    "Arts funding increased by 15%.",
    "News channels broadcast in HD.",
    "Government launched a digital ID program.",
    "Climate data published by the ministry.",
    "Healthcare insurance covers dental care.",
    "Tax returns are due in April.",
    "Remote work survey included 10,000 employees.",
    "Electric car charging stations doubled.",
    "Social media user base reached 4 billion.",
    "Parliament scheduled a debate on migration.",
    "Median rent is $1,100 per month.",
    "Public transport fares were reduced.",
    "School curriculum added environmental studies.",
    "Online privacy complaints rose by 8%.",
    "Food safety standards updated.",
    "Internet infrastructure expanded in rural areas.",
    "Mental health hotline launched.",
    "Renewable energy subsidies increased.",
    "Animal shelters received government funding.",
    "Living costs report published in June.",
    "Justice system budget approved.",
    "Media coverage focused on elections.",
    "Voting age is 18 years.",
    "Art festival held in September.",
    "City population reached 2 million.",
    "Education system includes online courses.",
    "Technology exports rose by 6%.",
    "Universal basic income discussed in committee.",
    "Second chance program evaluation released.",
    "Healthcare system includes telemedicine.",
    "Police force numbers increased.",
    "Environmental protection agency founded.",
    "Science awards presented in October.",
    "Freedom of speech law amended.",
    "Minimum wage review scheduled.",
    "Fashion industry jobs grew by 4%.",
    "Sports league expanded to 20 teams.",
    "Democracy index published annually.",
    "Recycling rates reached 60%.",
    "Internet security guidelines issued.",
    "Pension system reform proposed.",
    "Small business grants awarded.",
    "Public libraries open on Sundays.",
    "Travel visa requirements changed.",
    "Healthcare workers unionized.",
    "Justice system review completed.",
    "Education budget increased.",
    "Climate action targets set for 2028.",
    "Kindness campaign results published.",
    "Bike lane network mapped.",
    "Arts council awarded new grants.",
    "News app launched by major outlet."
]

def print_true_false_count(texts, category):
    true_count = 0
    false_count = 0
    for i, text in enumerate(texts):
        result = analyze_opinion(text, threshold=0.65)
        print(f"{category}: {text} -> {result}")
        if result == "Yes":  # Nur "Yes" als True zählen!
            true_count += 1
        else:
            false_count += 1
    print(f"{category}: Anzahl True = {true_count}, Anzahl False = {false_count}")

print_true_false_count(explizite, "Explizite Meinungen")
print_true_false_count(implizite, "Implizite Meinungen")
print_true_false_count(informationen, "Informationen/Fakten")

#Explizite Meinungen: Anzahl True = 50, Anzahl False = 0 (100%)
#Implizite Meinungen: Anzahl True = 133, Anzahl False = 16 (89,3%)
#Informationen/Fakten: Anzahl True = 1, Anzahl False = 148 (0,7%)